# Generated by Django 2.1.4 on 2019-01-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'slug')},
        ),
    ]
