# Generated by Django 2.1.4 on 2018-12-30 17:23

import blog2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0006_auto_20181230_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True, validators=[blog2.models.validate_author_email]),
        ),
    ]
