# Generated by Django 2.1.4 on 2018-12-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0007_post_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
